#! /bin/sh

cp ip-server.service /lib/systemd/system/ip-server.service
chmod 644 /lib/systemd/system/ip-server.service

systemctl daemon-reload
systemctl enable ip-server.service
systemctl start  ip-server.service

systemctl status ip-server.service
