# This node attempts to precisely localize the vehicle directly in the map

frequency: 20
sensor_timeout: 1
two_d_mode: false
print_diagnostics: true
publish_tf: true

map_frame: world
odom_frame: map
base_link_frame: base_link
world_frame: map

odom0: /probably_still
odom0_config:  [true, true, true,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]

#odom0: /odometry/gps
#odom0_config:  [true, true, true,
#                false, false, false,
#                true, true, true,
#                false, false, false,
#                false, false, false]
#odom0_nodelay: false
#odom0_differential: false
#odom0_relative: false

#imu0: /imu/data
#imu0_config:  [false, false, false,
#                true, true, true,
#                false, false, false,
#                true, true, true,
#                false, false, false]
#imu0_nodelay: false
#imu0_differential: false
#imu0_relative: false
# imu0_queue_size: 5
# imu0_pose_rejection_threshold: 0.8
# imu0_twist_rejection_threshold: 0.8
# imu0_linear_acceleration_rejection_threshold: 0.8